spring:
  application:
    name: claims-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/claims}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when-authorized
